version: '3.7'
services:
  core:
    build:
      context: ./core
    container_name: core
    ports:
      - 8000:8000
    volumes:
      - ./core:/core
    working_dir: /core
    command: python manage.py runserver 0:8000
    environment:
      - API_ENTRYPOINT=http://localhost:8000/graphql
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:11.2-alpine
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 9000:8080
volumes:
  pgdata:
